version: "3"
services:
 b_greets:
  image: docker_b_greets
  deploy:
   replicas: 5
   resources:
    limits:
     cpus: "0.1"
     memory: 50M
   restart_policy:
    condition: on-failure
  ports:
   - "8901:8888"
  networks:
   - webnet
   
networks:
 webnet:
